steps:
- name: 'ubuntu'
  id: Set image tag in deployment
  args:
  - 'sed'
  - '"s#image: gcr.*#image: gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA#"'
  - 'k8s/portfolio.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'k8s/portfolio.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
