apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:1.15.3-alpine
        name: nginx
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: "sites-enabled"
          mountPath: "/etc/nginx/sites-enabled"
        - name: "config"
          mountPath: "/etc/nginx/"
      volumes:
      - name: sites-enabled
        configMap:
          name: sites-enabled
      - name: config
        configMap:
          name: config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sites-enabled
data:
  gregoryguterman.com: |
      server {
        server_name gregoryguterman.com, www.gregoryguterman.com;
        listen 80 default_server;
        location / {
          proxy_pass http://portfolio.default.svc.cluster.local:3001;
        }
        location = /challenge-framework {
          return 302 /challenge-framework/;
        } # a little cheat to strip the path
        location /challenge-framework/ {
          proxy_pass http://challenge.default.svc.cluster.local:3001/;
        }
      }

  radioplaylist.live: |
      server {
        server_name radioplaylist.live www.radioplaylist.live;
        listen 80;
        location / {
          proxy_pass http://radio.default.svc.cluster.local:3002;
        }
      }

  codestory.xyz: |
      server {
        server_name codestory.xyz www.codestory.xyz;
        listen 80;
        location / {
          proxy_pass http://codestory-web.default.svc.cluster.local;
        }
        location /api {
          proxy_pass http://codestory-api.default.svc.cluster.local:3001;
        }
      }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      include /etc/nginx/sites-enabled/*;
      access_log /dev/stdout;
    }

